name = "kalaspace-nav"
main = "worker.js"
compatibility_date = "2024-09-23"

# KV namespace binding
[[kv_namespaces]]
binding = "BOOKMARKS_KV"
id = "4bd0999f83274f5c8ceef63042c015ba"

# Environment variables
[vars]
GITHUB_REPO = "qwerasdzx-123/kalaspace-nav"
AUTH_SECRET = "3299f346c33ba8a668a33787daa76ca02fe5f172669235c3b7eb546faa32a309"
